# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmc < Formula
  desc "CoinMarketCap CLI - cryptocurrency data at your fingertips"
  homepage "https://github.com/coinmarketcap-official/CoinMarketCap-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_amd64.tar.gz"
      sha256 "45c0d4158478776718d3fcd10a6ea7e9f687eb7ad1e44cdc88e7fb89cef301fa"

      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_arm64.tar.gz"
      sha256 "e39dbc8246776126f4d6f54d8062826ce7831aac9ec603b1541d73a6cf9d7dfa"

      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_amd64.tar.gz"
      sha256 "f1290982a1beafef5b19fc717c45c569a830561b06cb81d2230399fa3f316cc2"
      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_arm64.tar.gz"
      sha256 "753211c0c29b94704f328ab33bbf2f492d61aa2d5135cf5ccd9ec26bceebe859"
      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  test do
    system "#{bin}/cmc", "version"
  end
end
