# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmc < Formula
  desc "CoinMarketCap CLI - cryptocurrency data at your fingertips"
  homepage "https://github.com/coinmarketcap-official/CoinMarketCap-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_amd64.tar.gz"
      sha256 "68d7b3b6c4a0a70c8bd0b195800665bb1c1fd0422a1e627efd887ba1a5aec46d"

      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_arm64.tar.gz"
      sha256 "7f5fac4f747766df2a93775a1d48c7707ef30cc0edc57245b0d91e7ceb638591"

      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_amd64.tar.gz"
      sha256 "9f9568dd728e545d27386acf706d4518a0184cb29f93dda230554d44c9001843"
      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_arm64.tar.gz"
      sha256 "d63a91bf6661ddb8b778e7dc51a57e7eecd5e0b802cdfad6bacab203fd01358d"
      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  test do
    system "#{bin}/cmc", "version"
  end
end
