# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmc < Formula
  desc "CoinMarketCap CLI - cryptocurrency data at your fingertips"
  homepage "https://github.com/coinmarketcap-official/CoinMarketCap-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_amd64.tar.gz"
      sha256 "eb3e10952567d52156225a46dbb4226d82255d9f828780b630da9454b6a26b91"

      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_arm64.tar.gz"
      sha256 "43212d350472c97026b5cbc02c1917783f7f748388ee1ea94f7e59a868a22c45"

      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_amd64.tar.gz"
      sha256 "277763f7ab3b3c138ee7eb935e53fa5dd2a9c2b2787e6508642a5ed153af0964"
      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_arm64.tar.gz"
      sha256 "f2e5471e4a9fc23e37e6eae15f2ee8bcffd028db5e111afbb2bcab6bd56af6a1"
      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  test do
    system "#{bin}/cmc", "version"
  end
end
